spring:
    application:
        name: employee_spring_management
    data:
        web:
            pageable:
                one-indexed-parameters: true
    datasource:
        url: jdbc:mysql://localhost:3306/hr_management?allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 10MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME:your@gmail.com}
        password: ${MAIL_PASSWORD:your-app-password}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

jwt:
    secret: tuan_dao_jwt_secret_key_HS256_tuan_dao_jwt_secret_key_HS256_tuan_dao_jwt_secret_key_HS256
    # 1 ngay = 86400000ms
    access-token-expiration: 86400000
    # 7 ngay = 604800000ms
    refresh-expiration: 604800000

app:
    # Đặt true khi deploy HTTPS (production)
    cookie:
        secure: false
    upload:
        base-dir: ./uploads
        max-file-size: 5242880
        allowed-extensions:
            - jpg
            - jpeg
            - png
            - gif
            - webp
        allowed-folders:
            - avatars
            - logos
    seed-data: true

springdoc:
    swagger-ui:
        #lưu token vào Local Storage
        persist-authorization: true
        enabled: true
